# Generated by Django 5.1 on 2024-09-03 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_room_scheduler_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
